name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Enable corepack
      run: corepack enable
    - name: Install pnpm
      run: corepack prepare pnpm@latest --activate
    - name: Install dependencies
      run: pnpm i
    - name: Generate prisma client
      run: prisma generate
    - name: Build the app
      run: npm run build

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/pischule/shortener-js
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
